FROM node:20.18.0-alpine

ARG GIT_COMMIT
WORKDIR /usr/app

RUN apk add --no-cache git
COPY package.json ./
COPY yarn.lock ./
COPY .env ./
RUN yarn install
RUN yarn add @nestjs/axios
RUN yarn add @nestjs/schedule
RUN yarn add @nestjs/swagger
RUN yarn add class-validator
RUN yarn add @nestjs/jwt
RUN yarn add @nestjs/passport
RUN yarn add class-validator
COPY . .
RUN yarn build

EXPOSE 3000

CMD ["node", "dist/main"]
