name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build_image
        run: |
          docker build -t crafty-cotton-api:latest -f Dockerfile.local .

      - name: Run tests
        run: |
          docker run crafty-cotton-api:latest yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to Local Ubuntu and Deploy
        uses: appleboy/scp-action@master
        with:
          host: 172.19.172.52
          username: nadoo
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/nadoo/app"

      - name: SSH to Local Ubuntu and Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 172.19.172.52
          username: nadoo
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/nadoo/app
            docker-compose down
            docker-compose up -d --build
